### ISSUE TITLE
Will this code be licensed under an open source license?

### ISSUE THREAD

**Issue by Rubonnek** [jjiangweilan/TileMap_Outline_Generator#1]
Hello,

I'd like to study this code more in-depth and I'd also like to modify it at some point. I can't do so freely without if the copyright owner does not specify a license that allows me to do so.

**Comment by jjiangweilan** [comment]
Hi Rubonnek,

I just make it under GNU GPL3. I am glad you are interested in this code.

**Comment by Rubonnek** [comment]
Thanks.
